service: product-parser-worker

plugins:
  - serverless-dotenv-plugin
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-plugin-aws-alerts

build:
  esbuild: false

package:
  exclude:
    - test/**

custom:
  alerts:
    stages:
      - prod
    topics:
      alarm:
        topic: ${self:service}-${opt:stage}-alerts-alarm
        notifications:
          - protocol: email
            endpoint: ${env:ALERTS_EMAIL}
    alarms:
      - functionErrors
      - functionThrottles

useDotenv: true
provider:
  name: aws
  runtime: nodejs20.x

functions:
  products-pooling:
    handler: src/handler.run
    timeout: 120 # 2 minutes
    events:
      - schedule: cron(0 12 * * ? *)
