service: product-parser-worker

plugins:
  - serverless-plugin-typescript
  - serverless-offline

build:
  esbuild: false

package:
  exclude:
    - test/**

useDotenv: true
provider:
  name: aws
  runtime: nodejs20.x

functions:
  products-pooling:
    handler: src/handler.run
    events:
      - schedule: cron(0 12 * * ? *)
