service: product-parser-worker

plugins:
  - serverless-dotenv-plugin
  - serverless-plugin-typescript
  - serverless-offline

build:
  esbuild: false

package:
  exclude:
    - test/**

useDotenv: true
provider:
  name: aws
  runtime: nodejs20.x

  iamRoleStatements:
  - Effect: Allow
    Action:
      - sns:Publish
    Resource:
      - ${env:SNS_ERROR_ALERT_TOPIC}

functions:
  products-pooling:
    handler: src/handler.run
    timeout: 120 # 2 minutes
    events:
      - schedule: cron(0 12 * * ? *)
