service: product-parser-worker

plugins:
  - serverless-dotenv-plugin
  - serverless-plugin-typescript
  - serverless-offline

build:
  esbuild: false

package:
  exclude:
    - test/**

useDotenv: true
provider:
  name: aws
  runtime: nodejs20.x
  vpc:
    securityGroupIds:
      - sg-070a21954d1c79d82
    subnetIds:
      - subnet-0c54e85d3559dd9d8 # us-east-1a
      - subnet-0d72489791d5dfe32 # us-east-1b

functions:
  products-pooling:
    handler: src/handler.run
    events:
      - schedule: cron(0 12 * * ? *)
