service: product-parser-worker

custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    target: node20

package:
  individually: true
  exclude:
    - node_modules/**

useDotenv: true
provider:
  name: aws
  runtime: nodejs20.x

functions:
  products-pooling:
    handler: src/handler.run
    events:
      - schedule: cron(0 3 * * ? *)
